apiVersion: apps/v1
kind: Deployment
metadata:
  name: area-service
  namespace: gitlab-kubernetes-agent
spec:
  selector:
      matchLabels:
        app: area-service
  replicas: 1
  template:
    metadata:
      labels:
        app: area-service
    spec:
      containers:
        - name: area-service
          image: registry.gitlab.com/vallegrande/prs191_certidigital/ms-area:<VERSION>
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: registry-credentials
